CREATE DATABASE Trgovina;
GO

USE Trgovina;
GO

CREATE TABLE Kategorija (
    KategorijaID INT PRIMARY KEY IDENTITY(1,1),
    Naziv VARCHAR(50) NOT NULL
);

CREATE TABLE Proizvod (
    ProizvodID INT PRIMARY KEY IDENTITY(1,1),
    Naziv VARCHAR(100) NOT NULL,
    Cijena DECIMAL(10,2) NOT NULL,
    Kolicina INT NOT NULL DEFAULT 0,
    KategorijaID INT NOT NULL,
    FOREIGN KEY (KategorijaID) REFERENCES Kategorija(KategorijaID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE Kupac (
    KupacID INT PRIMARY KEY IDENTITY(1,1),
    Ime VARCHAR(50) NOT NULL,
    Prezime VARCHAR(50) NOT NULL
);

CREATE TABLE Narudzba (
    NarudzbaID INT PRIMARY KEY IDENTITY(1,1),
    KupacID INT NOT NULL,
    Datum DATE NOT NULL DEFAULT GETDATE(),
    Status VARCHAR(30) NOT NULL DEFAULT 'Na cekanju',
    FOREIGN KEY (KupacID) REFERENCES Kupac(KupacID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);

CREATE TABLE Stavka (
    StavkaID INT PRIMARY KEY IDENTITY(1,1),
    NarudzbaID INT NOT NULL,
    ProizvodID INT NOT NULL,
    Kolicina INT NOT NULL DEFAULT 1,
    FOREIGN KEY (NarudzbaID) REFERENCES Narudzba(NarudzbaID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (ProizvodID) REFERENCES Proizvod(ProizvodID)
        ON UPDATE CASCADE
        ON DELETE NO ACTION
);
